# Generated by Django 3.2 on 2021-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_Name', models.CharField(max_length=100)),
                ('service_Description', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=150)),
            ],
        ),
    ]
