# Generated by Django 3.2 on 2021-04-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_surgicalServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_Description',
            field=models.CharField(max_length=1100),
        ),
        migrations.CreateModel(
            name='specialistsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_Name', models.CharField(max_length=50)),
                ('specialist_LastName', models.CharField(max_length=50)),
                ('specialist_code', models.CharField(max_length=8)),
                ('specialist_Expertise', models.CharField(choices=[('E1', 'Cirugía Baríatrica'), ('E2', 'Obesidad'), ('E3', 'Trastornos de la Alimentación'), ('E4', 'Psicología de Salud')], default='select expertise', max_length=100)),
                ('specialist_Gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='select gender', max_length=50)),
                ('specialist_about', models.CharField(max_length=1100)),
                ('specialist_services', models.CharField(max_length=1100)),
                ('specialist_adress', models.CharField(max_length=100)),
                ('specialist_Edu', models.CharField(max_length=300)),
                ('fk_Services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_surgicalServices.services')),
            ],
        ),
    ]
